### ISSUE TITLE
How to submit multiple emails at once when call "EmailSubmission/set"?

### ISSUE THREAD

**Issue by FAE56** [fastmail/JMAP-Samples#23] opened 2022-11-04 09:47 UTC
I try to submit email A and B at a request. 
E1 has only one recipient R1, E2 has only one recipient R2, which are omitted in the request.
But the submission result is unexpected. R1 will receive E1, R2 will receive both E1 and E2.

```json
{ 
    "using":
    [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail",
        "urn:ietf:params:jmap:submission"
    ],
    "methodCalls":
    [
        [
            "EmailSubmission/set",
            {
                "accountId": "MY_ACCOUNT",
                "create":
                {
                    "0":
                    {
                        "identityId": "MY_IDENTITY",
                        "emailId": "E1"
                    },
                    "1":
                    {
                        "identityId": "MY_IDENTITY",
                        "emailId": "E2"
                    }
                },
                "onSuccessUpdateEmail":
                {
                    "#0":
                    {
                        "mailboxIds/MY_BOX1": true,
                        "mailboxIds/MY_BOX2": null,
                        "keywords/$draft", null

                    },
                    "#1":
                    {
                        "mailboxIds/MY_BOX1": true,
                        "mailboxIds/MY_BOX2": null,
                        "keywords/$draft", null
                    }
                }
            },
            "0"
        ]
    ]
}
```

**Comment by FAE56** [comment] 2022-11-04 10:07
Same behaviour when I use two method call in one request.
```json
{
    "using":
    [
        "urn:ietf:params:jmap:core",
        "urn:ietf:params:jmap:mail",
        "urn:ietf:params:jmap:submission"
    ],
    "methodCalls":
    [
        [
            "EmailSubmission/set",
            {
                "accountId": "MY_ACCOUNT",
                "create":
                {
                    "0":
                    {
                        "identityId": "MY_IDENTITY",
                        "emailId": "E1"
                    }
                },
                "onSuccessUpdateEmail":
                {
                    "#0":
                    {
                        "keywords/$draft": null,
                        "mailboxIds/MY_BOX1": null,
                        "mailboxIds/MY_BOX2": true
                    }
                }
            },
            "0"
        ],
        [
            "EmailSubmission/set",
            {
                "accountId": "MY_ACCOUNT",
                "create":
                {
                    "1":
                    {
                        "identityId": "MY_IDENTITY",
                        "emailId": "E2"
                    }
                },
                "onSuccessUpdateEmail":
                {
                    "#1":
                    {
                        "keywords/$draft": null,
                        "mailboxIds/MY_BOX1": null,
                        "mailboxIds/MY_BOX2": true
                    }
                }
            },
            "1"
        ]
    ]
}
```

**Comment by rjbs** [comment] 2022-11-04 12:42
I can't reproduce this problem using Fastmail's API.  I hacked up the "hello-world" program to attempt what you describe and it works with a single call.  

[send-two.txt](https://github.com/fastmail/JMAP-Samples/files/9938291/send-two.txt)

If you can provide a complete program that triggers this behavior, let me know.  I'm closing this issue for now, though.

**Comment by rjbs** [comment] 2022-11-04 16:21
Those two fake emails are real, what that program does is translate the username "x@y.com" to "x+1@y.com" and "x+2@y.com", which then works properly — but I bet the bug is being hidden by Cyrus message deduplication.  One of my colleagues has reproduced the problem, and we'll look into it.

**Closed** 2023-04-05 16:20 UTC
